export enum DomainErrorCode {
  ORDER_NOT_FOUND = 'ORDER_NOT_FOUND',
  ORDER_ALREADY_EXISTS = 'ORDER_ALREADY_EXISTS',
  ORDER_CREATE_FORBIDDEN = 'ORDER_CREATE_FORBIDDEN',
  ORDER_CREATE_INVALID_PAYLOAD = 'ORDER_CREATE_INVALID_PAYLOAD',
  ORDER_CONFIRM_FORBIDDEN = 'ORDER_CONFIRM_FORBIDDEN',
  ORDER_CONFIRM_INVALID_STATUS = 'ORDER_CONFIRM_INVALID_STATUS',
  ORDER_NOT_CHANGEABLE = 'ORDER_NOT_CHANGEABLE',
  ORDER_COMPLETED_NOT_CHANGEABLE = 'ORDER_COMPLETED_NOT_CHANGEABLE',

  CHANGE_REQUEST_NOT_FOUND = 'CHANGE_REQUEST_NOT_FOUND',
  CHANGE_REQUEST_CREATE_FORBIDDEN = 'CHANGE_REQUEST_CREATE_FORBIDDEN',
  CHANGE_REQUEST_REVIEW_FORBIDDEN = 'CHANGE_REQUEST_REVIEW_FORBIDDEN',
  CHANGE_REQUEST_EMPTY_CHANGES = 'CHANGE_REQUEST_EMPTY_CHANGES',
  CHANGE_REQUEST_INVALID_CHANGES = 'CHANGE_REQUEST_INVALID_CHANGES',
  CHANGE_REQUEST_INVALID_QUERY = 'CHANGE_REQUEST_INVALID_QUERY',
  CHANGE_REQUEST_QUANTITY_NOT_INCREASED = 'CHANGE_REQUEST_QUANTITY_NOT_INCREASED',
  CHANGE_REQUEST_DUE_DATE_TOO_SOON = 'CHANGE_REQUEST_DUE_DATE_TOO_SOON',
  CHANGE_REQUEST_PENDING_EXISTS = 'CHANGE_REQUEST_PENDING_EXISTS',
  CHANGE_REQUEST_PENDING_NOT_FOUND = 'CHANGE_REQUEST_PENDING_NOT_FOUND',
  CHANGE_REQUEST_NOT_PENDING = 'CHANGE_REQUEST_NOT_PENDING',
  CHANGE_REQUEST_ALREADY_CLOSED = 'CHANGE_REQUEST_ALREADY_CLOSED',
  CHANGE_REQUEST_REVIEW_COMMENT_REQUIRED = 'CHANGE_REQUEST_REVIEW_COMMENT_REQUIRED',

  ORDER_VERSION_NOT_FOUND = 'ORDER_VERSION_NOT_FOUND',
  ORDER_HISTORY_INVALID_QUERY = 'ORDER_HISTORY_INVALID_QUERY',
  ORDER_VERSION_AS_OF_NOT_FOUND = 'ORDER_VERSION_AS_OF_NOT_FOUND',
  ORDER_VERSION_COMPARE_TARGET_NOT_FOUND = 'ORDER_VERSION_COMPARE_TARGET_NOT_FOUND',

  APPROVAL_TRANSACTION_FAILED = 'APPROVAL_TRANSACTION_FAILED',
}

export type DomainErrorStage =
  | 'ORDER_CREATE'
  | 'ORDER_READ'
  | 'ORDER_CONFIRM'
  | 'CHANGE_REQUEST_CREATE'
  | 'CHANGE_REQUEST_REVIEW'
  | 'ORDER_HISTORY_READ'
  | 'ORDER_VERSION_COMPARE'
  | 'APPROVAL_TRANSACTION';
